name: Test Comment

on:
  pull_request:
    types:
      - opened
  issue_comment:
    types:
      - created
      - edited

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  notify:
    name: Notify 
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Add notification comment
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '배포를 원하시면 `/deploy`를 입력해주세요. 정보를 원하시면 `/info`를 입력해주세요.'
              });
            } catch (error) {
              console.error('Error creating comment:', error);
              process.exit(1);
            }

  process-comment:
    name: Process Comment
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Check command
        id: check-command
        run: |
          if [[ "${{ github.event.comment.body }}" == *"/deploy"* ]]; then
            echo "action=deploy" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.comment.body }}" == *"/info"* ]]; then
            echo "action=info" >> $GITHUB_OUTPUT
          fi

      - name: Process deploy command
        if: steps.check-command.outputs.action == 'deploy'
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Processing deploy command...');
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'deploy가 입력되었습니다.'
              });
              console.log('Comment created successfully');
            } catch (error) {
              console.error('Error creating comment:', error);
              process.exit(1);
            }

      - name: Process info command
        if: steps.check-command.outputs.action == 'info'
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Processing info command...');
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'info가 입력되었습니다.'
              });
              console.log('Comment created successfully');
            } catch (error) {
              console.error('Error creating comment:', error);
              process.exit(1);
            }